# description
name: "Leszek Orzeszek"
description: "Portfolio moje co≈õtam"
author: "Leszek Pietrzak"

# address settings
# url: "http://localhost:4000"
url: "http://smutnyleszek.github.io"
# url: "http://0.0.0.0:4000"
permalink: /project/:title

# site configuration
encoding: UTF-8
markdown: rdiscount
future: true
paginate: 9000
include: ['.htaccess']

# language settings
default-language: "pl-pl"
description-en-us: "Portfolio something stuff"

# site icons
icon-menu: '<i class="fa fa-bars"></i>'
icon-projects: '<i class="fa fa-archive"></i>'
icon-me: '<i class="fa fa-quote-right"></i>'
icon-contact: '<i class="fa fa-envelope"></i>'
icon-rss: '<i class="fa fa-rss"></i>'
icon-language: '<i class="fa fa-flag"></i>'

# category icons
icon-logo: '<i class="fa fa-cloud"></i>'
icon-website: '<i class="fa fa-globe"></i>'
icon-illustration: '<i class="fa fa-pencil"></i>'
icon-poster: '<i class="fa fa-file"></i>'
icon-typography: '<i class="fa fa-align-left"></i>'
icon-icon: '<i class="fa fa-folder"></i>'